Lint/NotNil:
  Description: Identifies usage of `not_nil!` calls
  Enabled: false
  Severity: Warning

Documentation/DocumentationAdmonition:
  Description: Reports documentation admonitions
  Enabled: false
  Severity: Warning

Naming/AccessorMethodName:
  Description: Makes sure that accessor methods are named properly
  Enabled: false
  Severity: Convention

Naming/QueryBoolMethods:
  Description: Reports boolean properties without the `?` suffix
  Enabled: false
  Severity: Convention

Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  Enabled: false
  Severity: Warning

Naming/BlockParameterName:
  Description: Disallows non-descriptive block parameter names
  Enabled: false
  Severity: Convention

Naming/PredicateName:
  Description: Disallows tautological predicate names
  Enabled: false
  Severity: Convention
